console.log("1) Stok miktari 500 kg uzerinde olan baliklarin isimleri nelerdir?");
console.log(fishNameOfRequestedValume(500));
console.log('2) Fiyat araligi 9Fr. ile 12 Fr. arasindaki baliklar hangileridir?');
console.log(fishFarmPriceInterwal(9, 12));
console.log('3) Sadece Bern\'de ve kis sezonu satilan baliklar hangileridir?');
console.log(fishFarmSaleLocationAndSeason('BE', 'Winter'));
console.log('4) Son kullanma tarihlerine gore baliklari siralayiniz. (Son kullanma tarihi yaklasan baliklar once gosterilmelidir)');
console.log(fishTypeSortByExpirationDate(fishFarm));
console.log('5) Avrupa Birligi\'nden (AB) gelen ve fiyati 10Fr dan dusuk olan baliklari alfabetik siraya gore siralayiniz');
console.log(fishTypeEuOriginAndLessPriceAlpeOrd(10, euList, fishFarm));
console.log('6) Toplam balik stoku ne kadardir?');
console.log(sumOfStocks(fishFarm));
console.log('7) En pahali olan balik hangisidir?');
console.log(maxPriceOfFish(fishFarm));
console.log('8) En uzun sureli durabilen baliklar hangi ulkeden gelmektedir?');
console.log(maxDurationFishOriginCountry(fishFarm));
console.log('9) Kis ve sonbahar sezonu icin swiss romande region\'da satilan baliklarin ortalama fiyati nedir?');
console.log(twoSeasonRegionalPriceMedian('Winter', 'Autumn', swissRomendeList, fishFarm));
console.log('10) Ticino Kantonu icin stokta toplam ne kadar balik mevcuttur?');
console.log(cantonStokTotal('TI', fishFarm));
console.log('11) Yazlik sezonda cikan ve AB disindan gelen ve de ZH\'de satilan baliklarin ortalama gramajini bulunuz?');
console.log(seasonalNotEUOriginCantonBaseitemWeightMedian('Summer', euList, 'ZH', fishFarm));